import type { AtlasNode, AtlasEdge, Branch, NodeType, Level, Status } from './types'

// ---------------------------------------------------------------------------
// Seed data. Uses Synphony's real examples from the brief so the space is
// populated and legible the first time you open it. Delete / edit freely —
// "Reset to seed" in Settings brings it back.
// ---------------------------------------------------------------------------

const now = Date.now()

function node(
  id: string,
  title: string,
  type: NodeType,
  level: Level,
  branchId: string,
  time: string,
  status: Status,
  owner: string,
  body: string,
): AtlasNode {
  return {
    id,
    title,
    body,
    type,
    level,
    status,
    branchId,
    owner,
    time,
    offset: { x: 0, y: 0, z: 0 },
    pinned: false,
    createdBy: owner,
    createdAt: now,
    updatedAt: now,
  }
}

export const seedBranches: Branch[] = [
  { id: 'b-china', name: 'China supply chain', color: '#f2789f', lane: -1 },
  { id: 'b-data', name: 'Robot data strategy', color: '#5aa9e6', lane: 0 },
  { id: 'b-gtm', name: 'Company & GTM', color: '#4bd0a0', lane: 1 },
]

export const seedNodes: AtlasNode[] = [
  // ----- China branch -----
  node(
    'n-china-strat',
    'Win information asymmetry in China',
    'strategy',
    'strategy',
    'b-china',
    '2026-02-01',
    'doing',
    'You',
    'The thesis: whoever understands the China hardware + robotics ecosystem before Western competitors gets a durable edge on cost, speed, and talent.\n\n**Why it matters**\n- Component cost is 3-5x cheaper on the ground.\n- Lead times collapse when you know the right suppliers.\n\nThis is a bet, not a task. Everything below is in service of it.',
  ),
  node(
    'n-china-hardware',
    'Access to cheap hardware in China',
    'strategy',
    'strategy',
    'b-china',
    '2026-03-01',
    'doing',
    'You',
    'Secure a repeatable pipeline for sourcing robot actuators, sensors, and compute at China prices.',
  ),
  node(
    'n-china-supplier',
    'Qualify 3 actuator suppliers in Shenzhen',
    'task',
    'project',
    'b-china',
    '2026-04-10',
    'doing',
    'You',
    'Deliverable: a short-list of 3 vetted suppliers with sample units in hand.\n\n- [ ] Shortlist from Alibaba + referrals\n- [ ] Request samples\n- [ ] Bench test torque + backlash',
  ),
  node(
    'n-china-trip',
    'Plan sourcing trip Q3',
    'task',
    'project',
    'b-china',
    '2026-08-01',
    'todo',
    'You',
    'On-the-ground week in Shenzhen. Depends on having a supplier shortlist to visit.',
  ),
  node(
    'n-email-jeff',
    'Email Jeff Monday re: customs broker',
    'task',
    'execution',
    'b-china',
    '2026-07-20',
    'todo',
    'You',
    'Jeff has a customs broker contact for importing sample units without the usual delay. Short email, ask for the intro.',
  ),
  node(
    'n-china-q',
    'Do we need an entity in HK?',
    'question',
    'execution',
    'b-china',
    '2026-07-18',
    'todo',
    'You',
    'Open question — an HK entity may simplify payments + IP, but adds overhead. Park here until we have supplier momentum.',
  ),

  // ----- Data strategy branch -----
  node(
    'n-data-strat',
    'How do we collect robot manipulation data?',
    'strategy',
    'strategy',
    'b-data',
    '2026-02-15',
    'doing',
    'You',
    'The core technical bet. Two credible paths, materially different in cost, scale, and data quality. We likely commit to one within a quarter.',
  ),
  node(
    'n-umi',
    'UMI-style handheld data collection',
    'decision',
    'strategy',
    'b-data',
    '2026-03-05',
    'idea',
    'You',
    'Cheap handheld grippers, collect demonstrations in the wild. Scales cheaply, but sim-to-real / embodiment gap is real.',
  ),
  node(
    'n-vla',
    'VLA teleoperation',
    'decision',
    'strategy',
    'b-data',
    '2026-03-05',
    'idea',
    'You',
    'Teleoperate the actual robot to gather on-embodiment data. Higher fidelity, much higher cost per hour.',
  ),
  node(
    'n-umi-proto',
    'Build UMI gripper prototype',
    'task',
    'project',
    'b-data',
    '2026-05-01',
    'todo',
    'You',
    'Deliverable: one working handheld gripper logging synced video + pose. Enough to judge data quality.',
  ),
  node(
    'n-teleop-rig',
    'Stand up a teleop rig',
    'task',
    'project',
    'b-data',
    '2026-05-20',
    'idea',
    'You',
    'Deliverable: an arm we can teleoperate end-to-end, measuring cost per demonstration-hour.',
  ),
  node(
    'n-jared',
    'Follow up with Jared on the eval harness',
    'task',
    'execution',
    'b-data',
    '2026-07-21',
    'blocked',
    'You',
    'Blocked on Jared — need his reply on which manipulation benchmark to standardise on before we can compare UMI vs VLA data.',
  ),

  // ----- Company / GTM branch -----
  node(
    'n-gtm-strat',
    'Find the wedge customer',
    'strategy',
    'strategy',
    'b-gtm',
    '2026-04-01',
    'idea',
    'You',
    'Who pays first, and for what narrow task? A sharp wedge beats a broad platform this early.',
  ),
  node(
    'n-hire',
    'First robotics hire',
    'task',
    'project',
    'b-gtm',
    '2026-06-15',
    'doing',
    'You',
    'Deliverable: signed offer with someone who has shipped a real manipulation stack.',
  ),
  node(
    'n-deck',
    'Refresh the one-pager',
    'task',
    'execution',
    'b-gtm',
    '2026-07-22',
    'todo',
    'You',
    'Tighten the narrative around the China + data bets so it reads in 60 seconds.',
  ),
]

export const seedEdges: AtlasEdge[] = [
  { id: 'e1', from: 'n-china-strat', to: 'n-china-hardware', kind: 'hierarchy' },
  { id: 'e2', from: 'n-china-hardware', to: 'n-china-supplier', kind: 'hierarchy' },
  { id: 'e3', from: 'n-china-supplier', to: 'n-china-trip', kind: 'hierarchy' },
  { id: 'e4', from: 'n-china-supplier', to: 'n-email-jeff', kind: 'hierarchy' },
  { id: 'e5', from: 'n-china-trip', to: 'n-china-supplier', kind: 'depends' },
  { id: 'e6', from: 'n-data-strat', to: 'n-umi', kind: 'hierarchy' },
  { id: 'e7', from: 'n-data-strat', to: 'n-vla', kind: 'hierarchy' },
  { id: 'e8', from: 'n-umi', to: 'n-umi-proto', kind: 'hierarchy' },
  { id: 'e9', from: 'n-vla', to: 'n-teleop-rig', kind: 'hierarchy' },
  { id: 'e10', from: 'n-umi-proto', to: 'n-jared', kind: 'depends' },
  { id: 'e11', from: 'n-teleop-rig', to: 'n-jared', kind: 'depends' },
  { id: 'e12', from: 'n-china-strat', to: 'n-data-strat', kind: 'relates' },
  { id: 'e13', from: 'n-gtm-strat', to: 'n-hire', kind: 'hierarchy' },
  { id: 'e14', from: 'n-gtm-strat', to: 'n-deck', kind: 'hierarchy' },
]
